# Runtime parameters 

# depth settings
string rt_force_depth #
string rt_min_depth #
string rt_max_depth #
string rt_ping_freq #
string rt_depth_mode #
string rt_detector_mode #
string rt_fm_disable #
string rt_log_watercol
string rt_extra_detect #
string rt_port_angle
string rt_stbd_angle
string rt_port_coverage
string rt_stbd_coverage

# txmit settings
string rt_pitch_stab #
string rt_tx_angle_along #
string rt_yaw_stab #
# string rt_heading_filter # VALUE NOT FOUND, WILL BE EMPTY
string rt_max_ping_rate #
string rt_min_swath_distance #
string rt_trigger #